### ISSUE TITLE
About Usage

### ISSUE THREAD

**Issue by aiyub007** [kosso/TiNSGIF#1]
Please Write something about usage of this thing. I don't know what to do after drag and drop TiNSGIF.xcodeproj to my project

**Comment by kosso** [comment]
Look at the example : https://github.com/kosso/TiNSGIF/tree/master/example/TiNSGIFTest/Resources

It's an iOS 'module' for the Appcelerator Titanium SDK.  Not for dropping into a regular Objective-C app.

**Comment by kosso** [comment]
If you're looking for the standard version of this library, you might want to try this : https://github.com/kosso/NSGIF
